# Generated by Django 6.0.3 on 2026-08-03 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_oauthprovider_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='What this key is used for.', max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('hashed_key', models.CharField(max_length=64)),
                ('read_only', models.BooleanField(default=False, help_text='Restrict this key to GET/HEAD/OPTIONS requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='apikey_user_created_idx')],
            },
        ),
    ]
