# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['provider__name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vatrate',
            options={'ordering': ['-valid_from', '-created_at', 'id']},
        ),
    ]
