# Generated by Django 6.0.8 on 2026-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_mfarecoverycode_totpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthprovider',
            name='require_mfa_claim',
            field=models.BooleanField(default=False, help_text="Refuse login unless the provider's userinfo response names an MFA method in its amr claim."),
        ),
    ]
