# Generated by Django 6.0.8 on 2026-09-20 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_oauthprovider_require_mfa_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='mfa_grace_period_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mfa_policy_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mfa_required_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.BigIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('aaguid', models.CharField(blank=True, default='', max_length=36)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
