# Generated by Django 6.0.8 on 2026-10-01 23:07

from django.db import migrations, models
from django.utils import timezone


def carry_over(apps, schema_editor):
    """#761: the 2FA policy becomes one switch, and self-setup a flag.

    A non-empty role list turns the switch on. Accounts the old list did not
    cover are now required too, so the policy counts as changed now and every
    account gets a full grace period instead of being locked out. Existing
    ``zev_owner`` accounts keep the self-setup they had.
    """
    AppSettings = apps.get_model("accounts", "AppSettings")
    for settings_row in AppSettings.objects.all():
        if settings_row.mfa_required_roles:
            settings_row.mfa_required = True
            settings_row.mfa_policy_changed_at = timezone.now()
            settings_row.save(update_fields=["mfa_required", "mfa_policy_changed_at"])
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="zev_owner").update(may_create_zev=True)


def carry_back(apps, schema_editor):
    """The closest earlier policy: required for the roles that could have it."""
    AppSettings = apps.get_model("accounts", "AppSettings")
    AppSettings.objects.filter(mfa_required=True).update(
        mfa_required_roles=["admin", "zev_owner", "participant", "guest"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_session_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='mfa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('invitation', 'Invitation')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='may_create_zev',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(carry_over, carry_back),
        migrations.RemoveField(
            model_name='appsettings',
            name='mfa_required_roles',
        ),
    ]
