# Generated by Django 6.0.7 on 2026-09-06 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zev', '0023_zev_itemize_tariff_bands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('annual_statements', 'Annual statements')], max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_expires_at', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, max_length=255, null=True, upload_to='exports/')),
                ('generated_count', models.PositiveIntegerField(blank=True, null=True)),
                ('omitted_count', models.PositiveIntegerField(blank=True, null=True)),
                ('omitted_participant_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='zev.zev')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['export_type', 'zev', 'created_at'], name='exports_exp_export__96f633_idx'), models.Index(fields=['status', 'started_at'], name='exports_exp_status_41129d_idx')],
            },
        ),
    ]
