"""Ordered token definitions for PDF and email template editors."""

# ── Invoice PDF catalog ──────────────────────────────────────────────────

_INVOICE_FIELDS = [
    {
        "group_key": "invoiceObject",
        "group_title_key": "admin.fields.invoiceObject",
        "fields": [
            {"variable": "{{ invoice.invoice_number }}", "description_key": "admin.fields.invoiceNumber", "sample_path": "invoice.invoice_number"},
            {"variable": "{{ invoice.zev.invoice_language|default:'de' }}", "description_key": "admin.fields.invoiceLanguage", "sample_path": "invoice.zev.invoice_language"},
            {"variable": "{{ invoice.get_status_display }}", "description_key": "admin.fields.invoiceStatus", "sample_path": "invoice.get_status_display"},
            {"variable": "{{ status_display }}", "description_key": "admin.fields.invoiceStatusDisplay", "sample_path": "status_display"},
            {"variable": "{{ invoice.subtotal_chf }}", "description_key": "admin.fields.subtotal", "sample_path": "invoice.subtotal_chf"},
            {"variable": "{{ invoice.vat_rate }}", "description_key": "admin.fields.vatRateFraction", "sample_path": "invoice.vat_rate"},
            {"variable": "{{ vat_rate_percent }}", "description_key": "admin.fields.vatRatePercent", "sample_path": "vat_rate_percent"},
            {"variable": "{{ invoice.vat_chf }}", "description_key": "admin.fields.vatAmount", "sample_path": "invoice.vat_chf"},
            {"variable": "{{ invoice.total_chf }}", "description_key": "admin.fields.total", "sample_path": "invoice.total_chf"},
            {"variable": "{{ invoice.notes }}", "description_key": "admin.fields.invoiceNotes", "sample_path": "invoice.notes"},
        ],
    },
    {
        "group_key": "formattedDates",
        "group_title_key": "admin.fields.formattedDates",
        "fields": [
            {"variable": "{{ formatted_dates.invoice_date }}", "description_key": "admin.fields.invoiceDate", "sample_path": "formatted_dates.invoice_date"},
            {"variable": "{{ formatted_dates.period_start }}", "description_key": "admin.fields.periodStart", "sample_path": "formatted_dates.period_start"},
            {"variable": "{{ formatted_dates.period_end }}", "description_key": "admin.fields.periodEnd", "sample_path": "formatted_dates.period_end"},
            {"variable": "{{ formatted_dates.due_date }}", "description_key": "admin.fields.dueDate", "sample_path": "formatted_dates.due_date"},
        ],
    },
    {
        "group_key": "participant",
        "group_title_key": "admin.fields.participant",
        "fields": [
            {"variable": "{{ participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "participant.full_name"},
            {"variable": "{{ participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "participant.address_line1"},
            {"variable": "{{ participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "participant.postal_code"},
            {"variable": "{{ participant.city }}", "description_key": "admin.fields.city", "sample_path": "participant.city"},
            {"variable": "{{ participant.email }}", "description_key": "admin.fields.email", "sample_path": "participant.email"},
        ],
    },
    {
        "group_key": "zev",
        "group_title_key": "admin.fields.zev",
        "fields": [
            {"variable": "{{ zev.name }}", "description_key": "admin.fields.zevName", "sample_path": "zev.name"},
            {"variable": "{{ zev.vat_number }}", "description_key": "admin.fields.vatNumber", "sample_path": "zev.vat_number"},
            {"variable": "{{ zev.bank_iban }}", "description_key": "admin.fields.bankIban", "sample_path": "zev.bank_iban"},
        ],
    },
    {
        "group_key": "ownerParticipant",
        "group_title_key": "admin.fields.ownerParticipant",
        "fields": [
            {"variable": "{{ owner_participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "owner_participant.full_name"},
            {"variable": "{{ owner_participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "owner_participant.address_line1"},
            {"variable": "{{ owner_participant.address_line2 }}", "description_key": "admin.fields.addressLine2", "sample_path": "owner_participant.address_line2"},
            {"variable": "{{ owner_participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "owner_participant.postal_code"},
            {"variable": "{{ owner_participant.city }}", "description_key": "admin.fields.city", "sample_path": "owner_participant.city"},
        ],
    },
    {
        "group_key": "lineItems",
        "group_title_key": "admin.fields.lineItems",
        "fields": [
            {"variable": "{% for group in grouped_items %}", "description_key": "admin.fields.groupLoop", "sample_path": "grouped_items.0.label"},
            {"variable": "{{ group.label }}", "description_key": "admin.fields.groupLabel", "sample_path": "grouped_items.0.label"},
            {"variable": "{{ group.subtotal }}", "description_key": "admin.fields.groupSubtotal", "sample_path": "grouped_items.0.subtotal"},
            {"variable": "{% for item in group.items %}", "description_key": "admin.fields.itemLoop", "sample_path": "grouped_items.0.items.0.description"},
            {"variable": "{{ item.description }}", "description_key": "admin.fields.itemDescription", "sample_path": "grouped_items.0.items.0.description"},
            {"variable": "{{ item.quantity_kwh }}", "description_key": "admin.fields.itemQuantity", "sample_path": "grouped_items.0.items.0.quantity_kwh"},
            {"variable": "{{ item.unit }}", "description_key": "admin.fields.itemUnit", "sample_path": "grouped_items.0.items.0.unit"},
            {"variable": "{{ item.unit_label }}", "description_key": "admin.fields.itemUnitLabel", "sample_path": "grouped_items.0.items.0.unit_label"},
            {"variable": "{{ item.unit_price_chf }}", "description_key": "admin.fields.itemUnitPrice", "sample_path": "grouped_items.0.items.0.unit_price_chf"},
            {"variable": "{{ item.total_chf }}", "description_key": "admin.fields.itemTotal", "sample_path": "grouped_items.0.items.0.total_chf"},
        ],
    },
    {
        "group_key": "invoiceNumberParts",
        "group_title_key": "admin.fields.invoiceNumberParts",
        "fields": [
            {"variable": "{{ invoice_number_prefix }}", "description_key": "admin.fields.invoicePrefix", "sample_path": "invoice_number_prefix"},
            {"variable": "{{ invoice_number_suffix }}", "description_key": "admin.fields.invoiceSuffix", "sample_path": "invoice_number_suffix"},
        ],
    },
    {
        "group_key": "chartsAndSavings",
        "group_title_key": "admin.fields.chartsAndSavings",
        "fields": [
            {"variable": "{{ energy_chart_svg|safe }}", "description_key": "admin.fields.energyChart", "sample_path": "energy_chart_svg"},
            {"variable": "{{ hourly_profile_chart_svg|safe }}", "description_key": "admin.fields.hourlyChart", "sample_path": "hourly_profile_chart_svg"},
            {"variable": "{{ energy_flow_svg|safe }}", "description_key": "admin.fields.energyFlowChart", "sample_path": "energy_flow_svg"},
            {"variable": "{{ qr_svg|safe }}", "description_key": "admin.fields.qrCode", "sample_path": "qr_svg"},
            {"variable": "{{ access_qr_svg|safe }}", "description_key": "admin.fields.accessQrCode", "sample_path": "access_qr_svg"},
            {"variable": "{{ savings_data.local_kwh }}", "description_key": "admin.fields.savingsLocalKwh", "sample_path": "savings_data.local_kwh"},
            {"variable": "{{ savings_data.local_chf }}", "description_key": "admin.fields.savingsLocalChf", "sample_path": "savings_data.local_chf"},
            {"variable": "{{ savings_data.local_rp }}", "description_key": "admin.fields.savingsLocalRp", "sample_path": "savings_data.local_rp"},
            {"variable": "{{ savings_data.grid_rp }}", "description_key": "admin.fields.savingsGridRp", "sample_path": "savings_data.grid_rp"},
            {"variable": "{{ savings_data.saved_rp }}", "description_key": "admin.fields.savingsSavedRp", "sample_path": "savings_data.saved_rp"},
            {"variable": "{{ savings_data.hypothetical_chf }}", "description_key": "admin.fields.savingsHypothetical", "sample_path": "savings_data.hypothetical_chf"},
            {"variable": "{{ savings_data.saved_chf }}", "description_key": "admin.fields.savingsSavedChf", "sample_path": "savings_data.saved_chf"},
            {"variable": "{{ savings_data.bar_pct }}", "description_key": "admin.fields.savingsBarPct", "sample_path": "savings_data.bar_pct"},
            {"variable": "{{ savings_data.savings_bar_pct }}", "description_key": "admin.fields.savingsSavingsBarPct", "sample_path": "savings_data.savings_bar_pct"},
        ],
    },
    {
        "group_key": "energySummary",
        "group_title_key": "admin.fields.energySummary",
        "fields": [
            {"variable": "{{ energy_summary.local_kwh }}", "description_key": "admin.fields.energySummaryLocal", "sample_path": "energy_summary.local_kwh"},
            {"variable": "{{ energy_summary.grid_kwh }}", "description_key": "admin.fields.energySummaryGrid", "sample_path": "energy_summary.grid_kwh"},
            {"variable": "{{ energy_summary.total_kwh }}", "description_key": "admin.fields.energySummaryTotal", "sample_path": "energy_summary.total_kwh"},
            {"variable": "{{ energy_summary.local_share_pct }}", "description_key": "admin.fields.energySummaryShare", "sample_path": "energy_summary.local_share_pct"},
        ],
    },
]


# ── Contract PDF catalog ─────────────────────────────────────────────────

_CONTRACT_FIELDS = [
    {
        "group_key": "participant",
        "group_title_key": "admin.fields.participant",
        "fields": [
            {"variable": "{{ participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "participant.full_name"},
            {"variable": "{{ participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "participant.address_line1"},
            {"variable": "{{ participant.address_line2 }}", "description_key": "admin.fields.addressLine2", "sample_path": "participant.address_line2"},
            {"variable": "{{ participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "participant.postal_code"},
            {"variable": "{{ participant.city }}", "description_key": "admin.fields.city", "sample_path": "participant.city"},
            {"variable": "{{ participant.phone }}", "description_key": "admin.fields.phone", "sample_path": "participant.phone"},
            {"variable": "{{ participant.email }}", "description_key": "admin.fields.email", "sample_path": "participant.email"},
        ],
    },
    {
        "group_key": "zev",
        "group_title_key": "admin.fields.zev",
        "fields": [
            {"variable": "{{ zev.name }}", "description_key": "admin.fields.zevName", "sample_path": "zev.name"},
            {"variable": "{{ zev.get_zev_type_display }}", "description_key": "admin.fields.zevType", "sample_path": "zev.get_zev_type_display"},
            {"variable": "{{ zev.grid_operator }}", "description_key": "admin.fields.gridOperator", "sample_path": "zev.grid_operator"},
            {"variable": "{{ zev.vat_number }}", "description_key": "admin.fields.vatNumber", "sample_path": "zev.vat_number"},
            {"variable": "{{ zev.bank_iban }}", "description_key": "admin.fields.bankIban", "sample_path": "zev.bank_iban"},
            {"variable": "{{ zev.payment_term_days }}", "description_key": "admin.fields.paymentTermDays", "sample_path": "zev.payment_term_days"},
        ],
    },
    {
        "group_key": "ownerParticipant",
        "group_title_key": "admin.fields.ownerParticipant",
        "fields": [
            {"variable": "{{ owner_participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "owner_participant.full_name"},
            {"variable": "{{ owner_participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "owner_participant.address_line1"},
            {"variable": "{{ owner_participant.address_line2 }}", "description_key": "admin.fields.addressLine2", "sample_path": "owner_participant.address_line2"},
            {"variable": "{{ owner_participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "owner_participant.postal_code"},
            {"variable": "{{ owner_participant.city }}", "description_key": "admin.fields.city", "sample_path": "owner_participant.city"},
            {"variable": "{{ owner_participant.phone }}", "description_key": "admin.fields.phone", "sample_path": "owner_participant.phone"},
            {"variable": "{{ owner_participant.email }}", "description_key": "admin.fields.email", "sample_path": "owner_participant.email"},
            {"variable": "{{ zev.owner.get_full_name }}", "description_key": "admin.fields.zevOwnerFullName", "sample_path": "zev.owner.get_full_name"},
            {"variable": "{{ zev.owner.username }}", "description_key": "admin.fields.zevOwnerUsername", "sample_path": "zev.owner.username"},
            {"variable": "{{ zev.owner.email }}", "description_key": "admin.fields.zevOwnerEmail", "sample_path": "zev.owner.email"},
        ],
    },
    {
        "group_key": "meteringPoints",
        "group_title_key": "admin.fields.meteringPoints",
        "fields": [
            {"variable": "{% for mp in consumption_mps %}", "description_key": "admin.fields.consumptionMpLoop", "sample_path": "consumption_mps.0.meter_id"},
            {"variable": "{% for mp in production_mps %}", "description_key": "admin.fields.productionMpLoop", "sample_path": "production_mps.0.meter_id"},
            {"variable": "{{ mp.meter_id }}", "description_key": "admin.fields.meterId", "sample_path": "consumption_mps.0.meter_id"},
            {"variable": "{{ mp.location_description }}", "description_key": "admin.fields.meterLocation", "sample_path": "consumption_mps.0.location_description"},
        ],
    },
    {
        "group_key": "tariffs",
        "group_title_key": "admin.fields.tariffs",
        "fields": [
            {"variable": "{% for row in local_tariff_rows %}", "description_key": "admin.fields.tariffLoop", "sample_path": "local_tariff_rows.0.name"},
            {"variable": "{{ row.name }}", "description_key": "admin.fields.tariffName", "sample_path": "local_tariff_rows.0.name"},
            {"variable": "{{ row.rate_rp }}", "description_key": "admin.fields.tariffRate", "sample_path": "local_tariff_rows.0.rate_rp"},
            {"variable": "{{ row.pct }}", "description_key": "admin.fields.tariffPct", "sample_path": "local_tariff_rows.0.pct"},
            {"variable": "{{ row.unit }}", "description_key": "admin.fields.tariffUnit", "sample_path": "local_tariff_rows.0.unit"},
            {"variable": "{{ row.rate_description }}", "description_key": "admin.fields.tariffRateDesc", "sample_path": "local_tariff_rows.0.rate_description"},
            {"variable": "{{ row.rate_note }}", "description_key": "admin.fields.tariffRateNote", "sample_path": "local_tariff_rows.0.rate_note"},
            {"variable": "{{ local_tariff_rows.0.name }}", "description_key": "admin.fields.firstTariffName", "sample_path": "local_tariff_rows.0.name"},
            {"variable": "{{ local_tariff_rows.0.rate_rp }}", "description_key": "admin.fields.firstTariffRate", "sample_path": "local_tariff_rows.0.rate_rp"},
            {"variable": "{{ local_tariff_rows.0.unit }}", "description_key": "admin.fields.firstTariffUnit", "sample_path": "local_tariff_rows.0.unit"},
            {"variable": "{{ row.valid_from }}", "description_key": "admin.fields.tariffValidFrom", "sample_path": "local_tariff_rows.0.valid_from"},
            {"variable": "{{ row.valid_to }}", "description_key": "admin.fields.tariffValidTo", "sample_path": "local_tariff_rows.0.valid_to"},
            {"variable": "{{ row.validity }}", "description_key": "admin.fields.tariffValidity", "sample_path": "local_tariff_rows.0.validity"},
            {"variable": "{{ row.notes }}", "description_key": "admin.fields.tariffNotes", "sample_path": "local_tariff_rows.0.notes"},
            {"variable": "{{ local_tariff_notes }}", "description_key": "admin.fields.localTariffNotes", "sample_path": "local_tariff_notes"},
        ],
    },
    {
        "group_key": "tariffClause",
        "group_title_key": "admin.fields.tariffClause",
        "fields": [
            {"variable": "{{ tariff_rule }}", "description_key": "admin.fields.tariffRule", "sample_path": "tariff_rule"},
            {"variable": "{{ tariff_pct_line }}", "description_key": "admin.fields.tariffPctLine", "sample_path": "tariff_pct_line"},
            {"variable": "{{ tariff_reference_product }}", "description_key": "admin.fields.tariffReferenceProduct", "sample_path": "tariff_reference_product"},
        ],
    },
    {
        "group_key": "contractDetails",
        "group_title_key": "admin.fields.contractDetails",
        "fields": [
            {"variable": "{{ contract_date }}", "description_key": "admin.fields.contractDate", "sample_path": "contract_date"},
            {"variable": "{{ participation_start }}", "description_key": "admin.fields.participationStart", "sample_path": "participation_start"},
            {"variable": "{{ document_id }}", "description_key": "admin.fields.documentId", "sample_path": "document_id"},
            {"variable": "{{ billing_interval_display }}", "description_key": "admin.fields.billingInterval", "sample_path": "billing_interval_display"},
            {"variable": "{{ vat_rate_display }}", "description_key": "admin.fields.vatRateDisplay", "sample_path": "vat_rate_display"},
            {"variable": "{{ additional_contract_notes }}", "description_key": "admin.fields.additionalNotes", "sample_path": "additional_contract_notes"},
            {"variable": "{{ lang }}", "description_key": "admin.fields.languageCode", "sample_path": "lang"},
        ],
    },
]


# ── Annual statement PDF catalog ─────────────────────────────────────────

_ANNUAL_STATEMENT_FIELDS = [
    {
        "group_key": "annualStatementData",
        "group_title_key": "admin.fields.annualStatementData",
        "fields": [
            {"variable": "{{ year }}", "description_key": "admin.fields.annualYear", "sample_path": "year"},
            {"variable": "{{ lang }}", "description_key": "admin.fields.languageCode", "sample_path": "lang"},
        ],
    },
    {
        "group_key": "participant",
        "group_title_key": "admin.fields.participant",
        "fields": [
            {"variable": "{{ participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "participant.full_name"},
            {"variable": "{{ participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "participant.address_line1"},
            {"variable": "{{ participant.address_line2 }}", "description_key": "admin.fields.addressLine2", "sample_path": "participant.address_line2"},
            {"variable": "{{ participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "participant.postal_code"},
            {"variable": "{{ participant.city }}", "description_key": "admin.fields.city", "sample_path": "participant.city"},
        ],
    },
    {
        "group_key": "zev",
        "group_title_key": "admin.fields.zev",
        "fields": [
            {"variable": "{{ zev.name }}", "description_key": "admin.fields.zevName", "sample_path": "zev.name"},
            {"variable": "{{ zev.vat_number }}", "description_key": "admin.fields.vatNumber", "sample_path": "zev.vat_number"},
        ],
    },
    {
        "group_key": "ownerParticipant",
        "group_title_key": "admin.fields.ownerParticipant",
        "fields": [
            {"variable": "{{ owner_participant.full_name }}", "description_key": "admin.fields.fullName", "sample_path": "owner_participant.full_name"},
            {"variable": "{{ owner_participant.address_line1 }}", "description_key": "admin.fields.addressLine1", "sample_path": "owner_participant.address_line1"},
            {"variable": "{{ owner_participant.address_line2 }}", "description_key": "admin.fields.addressLine2", "sample_path": "owner_participant.address_line2"},
            {"variable": "{{ owner_participant.postal_code }}", "description_key": "admin.fields.postalCode", "sample_path": "owner_participant.postal_code"},
            {"variable": "{{ owner_participant.city }}", "description_key": "admin.fields.city", "sample_path": "owner_participant.city"},
        ],
    },
    {
        "group_key": "annualTotals",
        "group_title_key": "admin.fields.annualTotals",
        "fields": [
            {"variable": "{{ totals.total_consumed_kwh }}", "description_key": "admin.fields.annualTotalConsumed", "sample_path": "totals.total_consumed_kwh"},
            {"variable": "{{ totals.from_zev_kwh }}", "description_key": "admin.fields.annualFromZev", "sample_path": "totals.from_zev_kwh"},
            {"variable": "{{ totals.from_grid_kwh }}", "description_key": "admin.fields.annualFromGrid", "sample_path": "totals.from_grid_kwh"},
            {"variable": "{{ totals.total_produced_kwh }}", "description_key": "admin.fields.annualTotalProduced", "sample_path": "totals.total_produced_kwh"},
            {"variable": "{{ totals.self_sufficiency_pct }}", "description_key": "admin.fields.annualSelfSufficiency", "sample_path": "totals.self_sufficiency_pct"},
        ],
    },
    {
        "group_key": "annualMonthlyData",
        "group_title_key": "admin.fields.annualMonthlyData",
        "fields": [
            {"variable": "{% for row in monthly_data %}", "description_key": "admin.fields.annualMonthlyLoop", "sample_path": "monthly_data.0.month_label"},
            {"variable": "{{ row.month_label }}", "description_key": "admin.fields.annualMonthLabel", "sample_path": "monthly_data.0.month_label"},
            {"variable": "{{ row.consumed_kwh }}", "description_key": "admin.fields.annualMonthConsumed", "sample_path": "monthly_data.0.consumed_kwh"},
            {"variable": "{{ row.from_zev_kwh }}", "description_key": "admin.fields.annualMonthFromZev", "sample_path": "monthly_data.0.from_zev_kwh"},
            {"variable": "{{ row.from_grid_kwh }}", "description_key": "admin.fields.annualMonthFromGrid", "sample_path": "monthly_data.0.from_grid_kwh"},
            {"variable": "{{ row.produced_kwh }}", "description_key": "admin.fields.annualMonthProduced", "sample_path": "monthly_data.0.produced_kwh"},
            {"variable": "{{ row.self_sufficiency_pct }}", "description_key": "admin.fields.annualMonthSelfSufficiency", "sample_path": "monthly_data.0.self_sufficiency_pct"},
        ],
    },
    {
        "group_key": "annualInvoices",
        "group_title_key": "admin.fields.annualInvoices",
        "fields": [
            {"variable": "{% for inv in invoices %}", "description_key": "admin.fields.annualInvoiceLoop", "sample_path": "invoices.0.invoice_number"},
            {"variable": "{{ inv.invoice_number }}", "description_key": "admin.fields.invoiceNumber", "sample_path": "invoices.0.invoice_number"},
            {"variable": "{{ inv.period_start_formatted }}", "description_key": "admin.fields.periodStart", "sample_path": "invoices.0.period_start_formatted"},
            {"variable": "{{ inv.period_end_formatted }}", "description_key": "admin.fields.periodEnd", "sample_path": "invoices.0.period_end_formatted"},
            {"variable": "{{ inv.status_display }}", "description_key": "admin.fields.invoiceStatus", "sample_path": "invoices.0.status_display"},
            {"variable": "{{ inv.subtotal_chf }}", "description_key": "admin.fields.subtotal", "sample_path": "invoices.0.subtotal_chf"},
            {"variable": "{{ inv.vat_chf }}", "description_key": "admin.fields.vatAmount", "sample_path": "invoices.0.vat_chf"},
            {"variable": "{{ inv.total_chf }}", "description_key": "admin.fields.total", "sample_path": "invoices.0.total_chf"},
            {"variable": "{{ invoice_totals.subtotal_chf }}", "description_key": "admin.fields.annualInvoiceTotalSubtotal", "sample_path": "invoice_totals.subtotal_chf"},
            {"variable": "{{ invoice_totals.vat_chf }}", "description_key": "admin.fields.annualInvoiceTotalVat", "sample_path": "invoice_totals.vat_chf"},
            {"variable": "{{ invoice_totals.total_chf }}", "description_key": "admin.fields.annualInvoiceTotalTotal", "sample_path": "invoice_totals.total_chf"},
        ],
    },
    {
        "group_key": "chartsAndSavings",
        "group_title_key": "admin.fields.chartsAndSavings",
        "fields": [
            {"variable": "{{ monthly_chart_svg|safe }}", "description_key": "admin.fields.annualMonthlyChart", "sample_path": "monthly_chart_svg"},
            {"variable": "{{ savings.local_kwh }}", "description_key": "admin.fields.savingsLocalKwh", "sample_path": "savings.local_kwh"},
            {"variable": "{{ savings.local_chf }}", "description_key": "admin.fields.annualSavingsLocalChf", "sample_path": "savings.local_chf"},
            {"variable": "{{ savings.local_rp }}", "description_key": "admin.fields.annualSavingsLocalRp", "sample_path": "savings.local_rp"},
            {"variable": "{{ savings.grid_rp }}", "description_key": "admin.fields.annualSavingsGridRp", "sample_path": "savings.grid_rp"},
            {"variable": "{{ savings.hypothetical_chf }}", "description_key": "admin.fields.annualSavingsHypothetical", "sample_path": "savings.hypothetical_chf"},
            {"variable": "{{ savings.saved_chf }}", "description_key": "admin.fields.savingsSavedChf", "sample_path": "savings.saved_chf"},
        ],
    },
    {
        "group_key": "formattedDates",
        "group_title_key": "admin.fields.formattedDates",
        "fields": [
            {"variable": "{{ formatted_dates.statement_date }}", "description_key": "admin.fields.annualStatementDate", "sample_path": "formatted_dates.statement_date"},
        ],
    },
]


# Only scalar keys used by the template are insertable; structured data is
# rendered through loops or lookups.

def _translation_group(keys: tuple[str, ...]) -> dict:
    return {
        "group_key": "translations",
        "group_title_key": "admin.fields.translations",
        "fields": [
            {
                "variable": f"{{{{ tr.{key} }}}}",
                "description_key": "admin.fields.trDescription",
                "sample_path": f"tr.{key}",
            }
            for key in keys
        ],
    }


_INVOICE_TRANSLATION_KEYS = (
    "access_description",
    "access_not_payment",
    "access_title",
    "amount",
    "billing_period",
    "category",
    "chart_description",
    "chart_title",
    "description",
    "due_date",
    "flow_description",
    "flow_title",
    "hourly_chart_description",
    "hourly_chart_title",
    "insights_page_intro",
    "insights_page_title",
    "invoice_date",
    "invoice_label",
    "kpi_grid_energy",
    "kpi_grid_hint",
    "kpi_local_energy",
    "kpi_local_hint",
    "kpi_savings_hint",
    "kpi_share",
    "kpi_share_hint",
    "notes_default",
    "notes_label",
    "notes_question",
    "payment_page_intro",
    "payment_page_title",
    "qty",
    "savings_from",
    "savings_grid_label",
    "savings_local_label",
    "savings_saved_label",
    "savings_solar_energy",
    "savings_title",
    "status",
    "subtotal",
    "thank_you",
    "to",
    "total",
    "unit_price",
    "vat",
)

_CONTRACT_TRANSLATION_KEYS = (
    "additional_label",
    "additional_placeholder",
    "agreements_title",
    "appendix_b_subtitle",
    "appendix_b_title",
    "appendix_title",
    "billing_interval_label",
    "clause_billing",
    "clause_billing_lead",
    "clause_tariff_adjustment",
    "clause_tariff_adjustment_lead",
    "clause_tariff_cap",
    "clause_tariff_cap_lead",
    "clause_tariff_rule_lead",
    "communication_text",
    "contract_date_label",
    "contract_title",
    "definitions_title",
    "duration_text",
    "duration_title",
    "field_address",
    "field_email",
    "field_meter",
    "field_meter_pv",
    "field_phone",
    "info_legal_title",
    "info_liability_text",
    "info_liability_title",
    "info_privacy_text",
    "info_privacy_title",
    "info_rights_title",
    "info_subtitle",
    "info_tariff_text",
    "info_tariff_title",
    "info_vzev_text",
    "info_vzev_title",
    "info_zev_text",
    "info_zev_title",
    "jurisdiction_text",
    "jurisdiction_title",
    "liability_text",
    "liability_title",
    "local_tariff_label",
    "local_tariff_note",
    "local_tariff_note_placeholder",
    "local_tariff_unit",
    "manager_text",
    "manager_title",
    "membership_text",
    "membership_title",
    "meter_hint",
    "meter_none",
    "metering_text",
    "metering_title",
    "owner_label",
    "page_label",
    "page_of",
    "participant_label",
    "participation_start_label",
    "parties_title",
    "payment_terms_label",
    "payment_terms_unit",
    "precedence_note",
    "privacy_controller_text",
    "privacy_controller_title",
    "privacy_purposes_title",
    "privacy_recipients_text",
    "privacy_recipients_title",
    "privacy_retention_col_data",
    "privacy_retention_col_period",
    "privacy_retention_title",
    "privacy_rights_title",
    "privacy_short",
    "privacy_text",
    "privacy_title",
    "reference_product_label",
    "sig_intro",
    "sig_owner",
    "sig_participant",
    "sig_place_date",
    "sig_signature",
    "signatures_title",
    "subject_text",
    "subject_title",
    "tariff_col_calc",
    "tariff_col_name",
    "tariff_col_price",
    "tariff_none",
    "tariff_valid_label",
    "vat_label",
    "vat_not_required",
    "vat_required",
)

_ANNUAL_STATEMENT_TRANSLATION_KEYS = (
    "autarky",
    "consumption_col",
    "from_grid",
    "from_grid_col",
    "from_label",
    "from_zev",
    "from_zev_col",
    "generated_on",
    "invoice_number_col",
    "invoices_title",
    "month_col",
    "monthly_breakdown",
    "monthly_chart_description",
    "no_invoices",
    "period_col",
    "production_col",
    "rp_unit",
    "savings_grid_label",
    "savings_local_label",
    "savings_saved_label",
    "savings_title",
    "self_sufficiency",
    "self_sufficiency_col",
    "statement_date",
    "subtotal_col",
    "title",
    "to_label",
    "total_col",
    "total_consumption",
    "total_label",
    "vat_col",
)

_INVOICE_FIELDS.append(_translation_group(_INVOICE_TRANSLATION_KEYS))
_CONTRACT_FIELDS.append(_translation_group(_CONTRACT_TRANSLATION_KEYS))
_ANNUAL_STATEMENT_FIELDS.append(_translation_group(_ANNUAL_STATEMENT_TRANSLATION_KEYS))


# ── Email catalogs ───────────────────────────────────────────────────────

_EMAIL_FIELDS = {
    "invoice_email": [
        {
            "group_key": "invoiceEmail",
            "group_title_key": None,
            "fields": [
                {"variable": "{invoice_number}", "description_key": "admin.emailTemplates.fields.invoiceNumber", "sample_path": "invoice_number"},
                {"variable": "{zev_name}", "description_key": "admin.emailTemplates.fields.zevName", "sample_path": "zev_name"},
                {"variable": "{participant_name}", "description_key": "admin.emailTemplates.fields.participantName", "sample_path": "participant_name"},
                {"variable": "{period_start}", "description_key": "admin.emailTemplates.fields.periodStart", "sample_path": "period_start"},
                {"variable": "{period_end}", "description_key": "admin.emailTemplates.fields.periodEnd", "sample_path": "period_end"},
                {"variable": "{due_date}", "description_key": "admin.emailTemplates.fields.dueDate", "sample_path": "due_date"},
                {"variable": "{total_chf}", "description_key": "admin.emailTemplates.fields.totalChf", "sample_path": "total_chf"},
            ],
        },
    ],
    "participant_onboarding": [
        {
            "group_key": "participantOnboarding",
            "group_title_key": None,
            "fields": [
                {"variable": "{participant_name}", "description_key": "admin.emailTemplates.fields.participantName", "sample_path": "participant_name"},
                {"variable": "{inviter_name}", "description_key": "admin.emailTemplates.fields.inviterName", "sample_path": "inviter_name"},
                {"variable": "{zev_name}", "description_key": "admin.emailTemplates.fields.zevName", "sample_path": "zev_name"},
                {"variable": "{link_url}", "description_key": "admin.emailTemplates.fields.onboardingLinkUrl", "sample_path": "link_url"},
                {"variable": "{expiry_date}", "description_key": "admin.emailTemplates.fields.expiryDate", "sample_path": "expiry_date"},
            ],
        },
    ],
    "email_verification": [
        {
            "group_key": "emailVerification",
            "group_title_key": None,
            "fields": [
                {"variable": "{verify_url}", "description_key": "admin.emailTemplates.fields.verifyUrl", "sample_path": "verify_url"},
            ],
        },
    ],
    "participant_magic_link": [
        {
            "group_key": "participantMagicLink",
            "group_title_key": None,
            "fields": [
                {"variable": "{participant_name}", "description_key": "admin.emailTemplates.fields.participantName", "sample_path": "participant_name"},
                {"variable": "{zev_name}", "description_key": "admin.emailTemplates.fields.zevName", "sample_path": "zev_name"},
                {"variable": "{link_url}", "description_key": "admin.emailTemplates.fields.linkUrl", "sample_path": "link_url"},
                {"variable": "{valid_minutes}", "description_key": "admin.emailTemplates.fields.validMinutes", "sample_path": "valid_minutes"},
            ],
        },
    ],
}
