server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  client_max_body_size 10m;

  error_page 413 /413.json;
  location = /413.json {
    default_type application/json;
    return 413 '{"detail":"File too large."}';
  }

  location / {
    try_files $uri /index.html;
  }
}
