# Generated by Django 6.0.3 on 2026-03-17 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('unit_identifier', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MeteringPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_id', models.CharField(help_text='Meter ID / MSCONS identifier from VNB', max_length=100)),
                ('ean', models.CharField(blank=True, help_text='EAN / Messpunkt-ID', max_length=20)),
                ('meter_type', models.CharField(choices=[('consumption', 'Consumption'), ('production', 'Production'), ('bidirectional', 'Bidirectional (Consumption + Production)')], default='consumption', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metering_points', to='zev.participant')),
            ],
            options={
                'ordering': ['meter_id'],
            },
        ),
        migrations.CreateModel(
            name='Zev',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('zev_type', models.CharField(choices=[('zev', 'ZEV (Zusammenschluss zum Eigenverbrauch)'), ('vzev', 'vZEV (Virtueller Zusammenschluss zum Eigenverbrauch)')], default='vzev', max_length=10)),
                ('grid_operator', models.CharField(blank=True, help_text='Name of the VNB (Verteilnetzbetreiber)', max_length=200)),
                ('grid_connection_point', models.CharField(blank=True, help_text='Verknüpfungspunkt / EAN', max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('invoice_counter', models.PositiveIntegerField(default=1, help_text='Auto-incremented invoice number')),
                ('bank_iban', models.CharField(blank=True, help_text='IBAN for QR-Rechnung', max_length=34)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_zevs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='zev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='zev.zev'),
        ),
    ]
