# Generated by Django 6.0.3 on 2026-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0002_meteringpoint_assignment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteringpoint',
            name='ean',
        ),
        migrations.AlterField(
            model_name='meteringpoint',
            name='meter_id',
            field=models.CharField(help_text='Messpunktnummer / Meter ID (e.g. CH9876543210987000000000044440859)', max_length=100),
        ),
    ]
