# Generated by Django 6.0.3 on 2026-03-17 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0003_remove_meteringpoint_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
