# Generated by Django 6.0.3 on 2026-03-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0005_participant_title_remove_unit_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zev',
            name='city',
        ),
    ]
