# Generated by Django 6.0.3 on 2026-03-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0007_zev_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
