# Generated by Django 6.0.3 on 2026-03-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0008_add_zev_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zev',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='zev',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='zev',
            name='city',
        ),
        migrations.RemoveField(
            model_name='zev',
            name='postal_code',
        ),
    ]
