# Generated by Django 6.0.3 on 2026-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0009_remove_zev_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='invoice_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('en', 'English')], default='de', help_text='Language used when generating invoice PDFs', max_length=2),
        ),
    ]
