# Generated by Django 6.0.3 on 2026-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0014_remove_meteringpoint_participant_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteringpoint',
            name='meter_id',
            field=models.CharField(help_text='Messpunktnummer / Meter ID (e.g. CH9876543210987000000000044440859)', max_length=100, unique=True),
        ),
    ]
