# Generated by Django 6.0.7 on 2026-07-29 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0015_meter_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='payment_term_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days after invoice generation (issue date) until payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='zev',
            name='email_body_template',
            field=models.TextField(blank=True, default='', help_text='Body template for invoice emails. Leave blank to use the system default. Available variables: {invoice_number}, {zev_name}, {participant_name}, {period_start}, {period_end}, {due_date}, {total_chf}.'),
        ),
        migrations.AlterField(
            model_name='zev',
            name='email_subject_template',
            field=models.CharField(blank=True, default='', help_text='Subject line template for invoice emails. Leave blank to use the system default. Available variables: {invoice_number}, {zev_name}, {participant_name}, {period_start}, {period_end}, {due_date}, {total_chf}.', max_length=500),
        ),
    ]
