# Generated by Django 6.0.3 on 2026-08-24 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0017_zev_contract_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringpointassignment',
            name='allocation_mode',
            field=models.CharField(choices=[('personal', 'Personal'), ('community', 'Community')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='allocation_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Unitless relative weight for splitting community-meter costs. Not a percentage, per-mille, or Wertquote.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
