# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0018_meteringpointassignment_allocation_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteringpointassignment',
            options={'ordering': ['-valid_from', '-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='zev',
            options={'ordering': ['name', 'id']},
        ),
    ]
