# Generated by Django 6.0.3 on 2026-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0019_alter_meteringpointassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='grid_operator_elcom_id',
            field=models.PositiveIntegerField(blank=True, help_text='ElCom operator id, when the grid operator was picked from the official list', null=True),
        ),
    ]
