# Generated by Django 6.0.3 on 2026-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0020_zev_grid_operator_elcom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='tariff_source_url',
            field=models.URLField(blank=True, help_text="URL of the grid operator's machine-readable tariff publication (VSE/AES standard)", max_length=500),
        ),
    ]
