# Generated by Django 6.0.8 on 2026-09-04 12:41

from django.db import migrations, models


def set_registered_where_vat_number(apps, schema_editor):
    """A ZEV that carried a VAT number was, by the old implicit rule, treated
    as VAT-registered — the engine added VAT whenever ``vat_number`` was set.
    Preserve that: those ZEVs move to the explicit ``registered`` mode. Every
    other ZEV keeps the ``not_registered`` default, which is the same 0% it
    had before. Nobody opts into ``inclusive`` automatically.
    """
    Zev = apps.get_model("zev", "Zev")
    Zev.objects.exclude(vat_number="").update(vat_mode="registered")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0021_zev_tariff_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='vat_mode',
            field=models.CharField(choices=[('not_registered', 'Not VAT-registered (prices are final as entered)'), ('registered', 'VAT-registered (VAT added on top of net prices)'), ('inclusive', 'Not registered — upstream VAT folded into prices')], default='not_registered', help_text='How VAT is applied when billing participants.', max_length=20),
        ),
        migrations.RunPython(set_registered_where_vat_number, noop_reverse),
    ]
