# Generated by Django 6.0.8 on 2026-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0022_zev_vat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='itemize_tariff_bands',
            field=models.BooleanField(default=False, help_text='Show each price band of a multi-band tariff as its own invoice line, instead of one line at the blended average rate.'),
        ),
    ]
