# Generated by Django 6.0.8 on 2026-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0023_zev_itemize_tariff_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='participant_invoice_access',
            field=models.BooleanField(default=False, help_text='Print a QR on invoices letting participants view them without an account.'),
        ),
    ]
