# Generated by Django 6.0.8 on 2026-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0024_zev_participant_invoice_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
