# Generated by Django 6.0.8 on 2026-09-12 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0025_zev_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantOnboardingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=32, unique=True)),
                ('secret', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tokens', to='zev.participant')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
