# Generated by Django 6.0.8 on 2026-09-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0026_participant_onboarding_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zev',
            name='disabled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this ZEV was disabled. Null means active.', null=True),
        ),
        migrations.AddField(
            model_name='zev',
            name='disabled_by',
            field=models.ForeignKey(blank=True, help_text='Who disabled this ZEV (its owner or an admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zev',
            name='disabled_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
