# Generated by Django 6.0.8 on 2026-09-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0029_one_live_onboarding_link_per_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteringpoint',
            name='has_behind_meter_generation',
            field=models.BooleanField(default=False, help_text='Generation (e.g. PV) sits behind this meter, so it records only the surplus fed in and the residual grid draw (net / surplus metering).'),
        ),
    ]
