# Generated by Django 6.0.8 on 2026-10-01 19:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def grant_owners(apps, schema_editor):
    """Every ZEV's owner becomes its manager (ADR 0027, spec §4.6).

    Lossless: ``Zev.owner`` is exactly the input. The grant starts on the day
    the ZEV was created, which is never in the future — starting it on
    ``start_date`` would lock the owner of a ZEV planned to start later out of
    it until then.
    """
    Zev = apps.get_model("zev", "Zev")
    ZevAccessGrant = apps.get_model("zev", "ZevAccessGrant")
    ZevAccessGrant.objects.bulk_create(
        ZevAccessGrant(
            zev_id=zev_id,
            user_id=owner_id,
            role="manager",
            valid_from=django.utils.timezone.localtime(created_at).date(),
        )
        for zev_id, owner_id, created_at in Zev.objects.values_list("id", "owner_id", "created_at").iterator()
    )


def drop_grants(apps, schema_editor):
    apps.get_model("zev", "ZevAccessGrant").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0030_meteringpoint_has_behind_meter_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZevAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('viewer', 'Viewer')], max_length=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who granted it; empty for grants created by migration or by owning the ZEV.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zev_grants', to=settings.AUTH_USER_MODEL)),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='zev.zev')),
            ],
            options={
                'ordering': ['zev_id', 'role', 'user_id', 'valid_from', 'id'],
                'indexes': [models.Index(fields=['user', 'valid_to'], name='zev_grant_user_valid_to')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('zev', 'user'), name='one_open_zev_grant_per_user'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='zev_grant_valid_window')],
            },
        ),
        migrations.RunPython(grant_owners, drop_grants),
    ]
