# Generated by Django 6.0.8 on 2026-10-02 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0034_participant_party_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZevPartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('issuer', 'Issuer'), ('representative', 'Representative'), ('landowner', 'Landowner')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='zev.party')),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_roles', to='zev.zev')),
            ],
            options={
                'ordering': ['role', '-valid_from', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='party_role_window_order'), models.UniqueConstraint(condition=models.Q(('role__in', ['issuer', 'representative']), ('valid_to__isnull', True)), fields=('zev', 'role'), name='one_open_single_holder_role'), models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('zev', 'party', 'role'), name='one_open_role_per_party')],
            },
        ),
    ]
