# Generated by Django 6.0.8 on 2026-10-02 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0037_remove_zev_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.ForeignKey(blank=True, help_text="The party's own account, when it is not a participant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
