# Generated by Django 6.0.8 on 2026-10-04 12:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zev', '0039_end_grants_covered_by_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('egid', models.PositiveIntegerField(blank=True, help_text='Federal building ID (EGID)', null=True, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='zevpartyrole',
            name='one_open_role_per_party',
        ),
        migrations.AlterField(
            model_name='meteringpoint',
            name='location_description',
            field=models.CharField(blank=True, help_text='Unit within the building (flat, floor, common areas)', max_length=200),
        ),
        migrations.AddField(
            model_name='building',
            name='zev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='zev.zev'),
        ),
        migrations.AddField(
            model_name='meteringpoint',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='metering_points', to='zev.building'),
        ),
        migrations.AddField(
            model_name='zevpartyrole',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landowner_roles', to='zev.building'),
        ),
        migrations.AddConstraint(
            model_name='zevpartyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('building__isnull', False), ('valid_to__isnull', True)), fields=('zev', 'party', 'role', 'building'), name='one_open_role_per_party_building'),
        ),
        migrations.AddConstraint(
            model_name='zevpartyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('building__isnull', True), ('valid_to__isnull', True)), fields=('zev', 'party', 'role'), name='one_open_role_per_party_without_building'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(condition=models.Q(('egid__isnull', False)), fields=('zev', 'egid'), name='unique_building_egid_per_zev'),
        ),
    ]
