[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
pythonpath = backend
python_files = tests.py test_*.py *_tests.py
addopts = -q -n auto --dist=worksteal
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests that exercise multiple components together
