{{- if not .Values.media.pvc.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openzev.mediaClaimName" . }}
  labels:
    {{- include "openzev.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.media.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.media.pvc.size }}
  {{- if .Values.media.pvc.storageClassName }}
  storageClassName: {{ .Values.media.pvc.storageClassName }}
  {{- end }}
{{- end }}
