# Generated by Django 6.0.3 on 2026-03-17 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('energy_type', models.CharField(choices=[('local', 'Local (Solar/ZEV)'), ('grid', 'Grid (Netzstrom)'), ('feed_in', 'Feed-in (Einspeisung)')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='zev.zev')),
            ],
            options={
                'ordering': ['zev', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TariffPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('flat', 'Flat rate (all hours)'), ('high', 'High tariff (HT)'), ('low', 'Low tariff (NT)')], default='flat', max_length=10)),
                ('price_chf_per_kwh', models.DecimalField(decimal_places=5, max_digits=8)),
                ('time_from', models.TimeField(blank=True, help_text='Start of this period (HH:MM)', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='End of this period (HH:MM)', null=True)),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated weekday numbers 0-6 (Mon-Sun). Leave blank for all days.', max_length=20)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['period_type'],
            },
        ),
    ]
