# Generated by Django 6.0.3 on 2026-07-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_add_metering_tariff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='billing_mode',
            field=models.CharField(choices=[('energy', 'By energy'), ('percentage_of_energy', 'Percentage of energy tariffs'), ('monthly_fee', 'Monthly fee'), ('yearly_fee', 'Yearly fee'), ('per_metering_point_monthly_fee', 'Per metering point monthly fee'), ('per_metering_point_yearly_fee', 'Per metering point yearly fee'), ('shared_monthly_fee', 'Shared monthly fee (split across participants)'), ('shared_yearly_fee', 'Shared yearly fee (split across participants)')], default='energy', max_length=40),
        ),
    ]
