# Generated by Django 6.0.3 on 2026-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0006_add_shared_fee_billing_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='split_key',
            field=models.CharField(choices=[('equal', 'Equal (headcount)'), ('weight', 'Weight')], default='equal', max_length=10),
        ),
    ]
