# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0007_tariff_split_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['zev', 'category', 'name', '-valid_from', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tariffperiod',
            options={'ordering': ['period_type', 'id']},
        ),
    ]
