# Generated by Django 6.0.3 on 2026-09-03 05:52

import tariffs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0008_alter_tariff_options_alter_tariffperiod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffperiod',
            name='months',
            field=models.CharField(blank=True, help_text='Comma-separated month numbers 1-12. Leave blank for all months.', max_length=40, validators=[tariffs.models.validate_month_list]),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='weekdays',
            field=models.CharField(blank=True, help_text='Comma-separated weekday numbers 0-6 (Mon-Sun). Leave blank for all days.', max_length=20, validators=[tariffs.models.validate_weekday_list]),
        ),
    ]
