# Generated by Django 6.0.8 on 2026-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0009_tariffperiod_months'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffperiod',
            options={'ordering': ['period_type', models.OrderBy(models.F('time_from'), nulls_first=True), 'id']},
        ),
        migrations.AddField(
            model_name='tariffperiod',
            name='label',
            field=models.CharField(blank=True, help_text="Name for this band, e.g. 'Peak'. Only used for period type 'band'.", max_length=60),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='period_type',
            field=models.CharField(choices=[('flat', 'Flat rate (all hours)'), ('high', 'High tariff (HT)'), ('low', 'Low tariff (NT)'), ('band', 'Time band')], default='flat', max_length=10),
        ),
    ]
