# Generated by Django 6.0.8 on 2026-09-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0010_tariffperiod_band_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='source_component',
            field=models.CharField(blank=True, choices=[('base', 'Base price (Grundpreis)'), ('energy', 'Energy price (Arbeitspreis)')], default='', help_text='Which price of the published entry this was imported from.', max_length=20),
        ),
        migrations.AddField(
            model_name='tariff',
            name='source_series_name',
            field=models.CharField(blank=True, default='', help_text="The operator's own name for this component, before the name suffix.", max_length=200),
        ),
    ]
