# Generated by Django 6.0.8 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0011_tariff_source_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTariffSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Shown when picking a source, e.g. 'Groupe E vario — grid'", max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('adapter', models.CharField(choices=[('vse_v1', 'VSE standard (v1)'), ('groupe_e', 'Groupe E'), ('bkw', 'BKW')], default='vse_v1', max_length=20)),
                ('tariff_type', models.CharField(choices=[('electricity', 'Electricity supply'), ('grid', 'Grid usage'), ('integrated', 'Integrated (electricity + grid)'), ('regional_fees', 'Regional fees'), ('feed_in', 'Feed-in remuneration')], max_length=20)),
                ('tariff_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_fetch_status', models.CharField(choices=[('pending', 'Not fetched yet'), ('ok', 'Fetched'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_error', models.CharField(blank=True, default='', max_length=500)),
                ('covers_from', models.DateTimeField(blank=True, null=True)),
                ('covers_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label', 'id'],
                'constraints': [models.UniqueConstraint(fields=('url', 'tariff_type', 'tariff_name'), name='unique_dynamic_tariff_source')],
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='dynamic_source',
            field=models.ForeignKey(blank=True, help_text='Price series this tariff is billed from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='tariffs.dynamictariffsource'),
        ),
        migrations.CreateModel(
            name='DynamicPricePoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(help_text='Start of the priced interval (UTC)')),
                ('valid_to', models.DateTimeField(help_text='End of the priced interval, exclusive (UTC)')),
                ('price_chf_per_kwh', models.DecimalField(decimal_places=5, max_digits=8)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tariffs.dynamictariffsource')),
            ],
            options={
                'ordering': ['source', 'valid_from', 'id'],
                'indexes': [models.Index(fields=['source', 'valid_from'], name='dyn_price_source_from_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'valid_from'), name='unique_dynamic_price_point')],
            },
        ),
    ]
