# Generated by Django 6.0.8 on 2026-09-11 21:59

from django.db import migrations, models
from django.db.models import F


def reject_invalid_intervals(apps, schema_editor):
    DynamicPricePoint = apps.get_model("tariffs", "DynamicPricePoint")
    points = DynamicPricePoint.objects.using(schema_editor.connection.alias)
    invalid = list(
        points.filter(valid_to__lte=F("valid_from"))
        .values_list("pk", "valid_from", "valid_to")[:10]
    )
    if invalid:
        details = ", ".join(
            f"{pk} ({valid_from} >= {valid_to})"
            for pk, valid_from, valid_to in invalid
        )
        raise RuntimeError(
            "Cannot add dynamic price interval validity constraint; fix these "
            f"billing-evidence rows first: {details}"
        )

    previous_source, previous_end = None, None
    for pk, source, start, end in points.order_by("source_id", "valid_from").values_list(
        "pk", "source_id", "valid_from", "valid_to"
    ).iterator():
        if source == previous_source and start < previous_end:
            raise RuntimeError(
                f"Overlapping dynamic price evidence at row {pk}, source {source}. "
                "Reconcile these intervals with retained invoices before migrating."
            )
        previous_source, previous_end = source, end


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0013_generic_dynamic_api_versions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dynamicpricepoint',
            name='dyn_price_source_from_idx',
        ),
        migrations.RunPython(reject_invalid_intervals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='dynamicpricepoint',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gt', models.F('valid_from'))), name='dynamic_price_point_valid_range'),
        ),
        migrations.AddField(
            model_name="dynamictariffsource",
            name="recovery_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamictariffsource",
            name="empty_on_not_found",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Treat HTTP 404 as a successful empty publication for this endpoint."
                ),
            ),
        ),
        migrations.AddField(
            model_name="dynamictariffsource",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Disabled sources remain as billing evidence but are skipped by scheduled refreshes."
                ),
            ),
        ),
    ]
