# Generated by Django 6.0.8 on 2026-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0015_source_version_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='minimum_price_chf_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Floor for a fetched feed-in series: the greater of this and the fetched price is billed.', max_digits=8, null=True),
        ),
    ]
