# Generated by Django 6.0.8 on 2026-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0016_minimum_price_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictariffsource',
            name='api_version',
            field=models.CharField(choices=[('v1_0_5', 'v1.0.5'), ('v2_0_0', 'v2.0.0'), ('bfe_rmp', 'BFE reference market price')], default='v1_0_5', max_length=20),
        ),
    ]
