# Generated by hand for SPEC-2026-percentage-tariff-bands.
#
# Moves the percentage of a percentage-of-energy tariff off ``Tariff`` and onto
# its ``TariffPeriod`` bands, so a percentage tariff can carry several
# time-of-use bands exactly like an energy tariff. Every existing single
# percentage becomes one flat band, so a tariff that had no bands before this
# migration bills exactly as it did.
#
# Deviation from the spec: §4.3 describes this as *one* migration file
# (schema + data + constraint + drop, in that order). Doing that in one
# transaction fails on PostgreSQL: the ``RunPython`` step deletes/creates
# ``TariffPeriod`` rows, which leaves deferred foreign-key trigger events
# pending on that table for the rest of the transaction, and PostgreSQL
# refuses an ``ALTER TABLE ... ADD CONSTRAINT`` on a table with pending
# trigger events in the same transaction (verified against the dev stack's
# Postgres: ``OperationalError: cannot ALTER TABLE "tariffs_tariffperiod"
# because it has pending trigger events``). The constraint and the
# ``RemoveField`` therefore move to a second migration, ``0019_
# percentage_bands_constraint``, so they run in their own transaction after
# this one has committed. Every operation, and the forward/backward
# semantics below, are otherwise exactly as specified.
#
# Order matters: the field is added and the price column relaxed *before* the
# data migration runs. Because schema and data operations share this
# migration, Django reverses them in order, so the backwards RunPython below
# runs after ``0019``'s reversal has re-added ``Tariff.percentage`` and
# dropped the constraint, and before this migration's own ``AlterField``
# reversal puts the (non-nullable) ``price_chf_per_kwh`` column back.

import django.core.validators
from django.db import migrations, models


def _flat_band_percentage(tariff):
    """The representative percentage for a rollback: flat, else high, else
    the first band by the model's own ordering."""
    bands = list(tariff.periods.order_by("period_type", "time_from", "id"))
    if not bands:
        return None
    flat = next((band for band in bands if band.period_type == "flat"), None)
    if flat is not None:
        return flat.percentage
    high = next((band for band in bands if band.period_type == "high"), None)
    if high is not None:
        return high.percentage
    return bands[0].percentage


def convert_percentage_to_bands(apps, schema_editor):
    Tariff = apps.get_model("tariffs", "Tariff")
    TariffPeriod = apps.get_model("tariffs", "TariffPeriod")
    db_alias = schema_editor.connection.alias

    tariffs = Tariff.objects.using(db_alias).filter(billing_mode="percentage_of_energy")
    for tariff in tariffs:
        # The serializer has always rejected bands on a percentage tariff, so
        # none should exist. A row created by hand through the admin could
        # still carry some; they were never billed (the engine ignored them
        # for this billing mode), so they are removed rather than kept
        # alongside the new flat band.
        TariffPeriod.objects.using(db_alias).filter(tariff=tariff).delete()
        if tariff.percentage is None:
            continue
        TariffPeriod.objects.using(db_alias).create(
            tariff=tariff,
            period_type="flat",
            percentage=tariff.percentage,
            price_chf_per_kwh=None,
        )


def restore_percentage_from_bands(apps, schema_editor):
    Tariff = apps.get_model("tariffs", "Tariff")
    db_alias = schema_editor.connection.alias

    tariffs = Tariff.objects.using(db_alias).filter(billing_mode="percentage_of_energy")
    for tariff in tariffs:
        tariff.percentage = _flat_band_percentage(tariff)
        tariff.save(using=db_alias, update_fields=["percentage"])
        tariff.periods.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0017_bfe_reference_price_api_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffperiod',
            name='percentage',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True,
                help_text=(
                    "Percentage of all grid energy tariffs used as the effective price. "
                    "Only for percentage-of-energy tariffs."
                ),
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='price_chf_per_kwh',
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=8, null=True,
                help_text=(
                    "Price in CHF per kWh. Required on a band of an energy tariff, "
                    "and must be null on a percentage-of-energy tariff."
                ),
            ),
        ),
        migrations.RunPython(convert_percentage_to_bands, restore_percentage_from_bands),
    ]
