# Generated by hand for SPEC-2026-percentage-tariff-bands.
#
# Continues 0018_percentage_bands in a second migration (and therefore a
# second transaction) purely to satisfy PostgreSQL — see the long comment at
# the top of that migration. Adds the "exactly one of price/percentage" DB
# constraint now that every row satisfies it, then drops the now-unused
# ``Tariff.percentage`` column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0018_percentage_bands'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tariffperiod',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('percentage__isnull', True), ('price_chf_per_kwh__isnull', False)),
                    models.Q(('percentage__isnull', False), ('price_chf_per_kwh__isnull', True)),
                    _connector='OR',
                ),
                name='tariffperiod_exactly_one_price',
            ),
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='percentage',
        ),
    ]
