# Generated by Django 6.0.8 on 2026-09-21 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zev', '0026_participant_onboarding_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('local', 'Local directory'), ('s3', 'S3-compatible storage')], default='local', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('bucket', models.CharField(blank=True, default='', max_length=255)),
                ('prefix', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('endpoint_url', models.URLField(blank=True, default='', max_length=500)),
                ('access_key_id', models.CharField(blank=True, default='', max_length=128)),
                ('secret_access_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('server_side_encryption', models.CharField(blank=True, default='AES256', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('instance', 'Whole instance'), ('zev', 'One ZEV')], default='instance', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('pre_restore', 'Before a restore')], default='manual', max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_name', models.CharField(blank=True, default='', max_length=255)),
                ('archive_location', models.CharField(blank=True, default='', max_length=1000)),
                ('archive_bytes', models.BigIntegerField(blank=True, null=True)),
                ('archive_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('encryption_key_fingerprint', models.CharField(blank=True, default='', max_length=16)),
                ('manifest_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='backups.backupdestination')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
                ('zev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to='zev.zev')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='backups_bac_status_f6b2cc_idx'), models.Index(fields=['scope', 'created_at'], name='backups_bac_scope_ad9595_idx')],
            },
        ),
    ]
