# Generated by Django 6.0.8 on 2026-09-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_restorejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdestination',
            name='retention_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='artifact_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='artifact_deleted_reason',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='file_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='verification_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='verification_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='verify_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
