# Generated by Django 6.0.3 on 2026-03-17 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_local_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_grid_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_feed_in_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal_chf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('vat_chf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_chf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='zev.participant')),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='zev.zev')),
            ],
            options={
                'ordering': ['-period_end', 'participant'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('local_energy', 'Local Energy (Solar)'), ('grid_energy', 'Grid Energy (Netzstrom)'), ('feed_in', 'Feed-in Credit'), ('fee', 'Fee'), ('credit', 'Credit')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unit_price_chf', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('total_chf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'item_type'],
            },
        ),
    ]
