# Generated by Django 6.0.3 on 2026-04-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_email_template'),
        ('zev', '0014_remove_meteringpoint_participant_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='zev.participant'),
        ),
    ]
