# Generated by Django 6.0.8 on 2026-08-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_contract_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-period_end", "participant", "id"]},
        ),
    ]
