# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractissue',
            options={'ordering': ['-version', 'id']},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['sort_order', 'item_type', 'description', 'id']},
        ),
    ]
