# Generated by Django 6.0.8 on 2026-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_contractissue_options_alter_emaillog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='embedded_vat_chf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
