# Generated by Django 6.0.8 on 2026-09-06 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_embedded_vat_chf'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=32, unique=True)),
                ('hashed_secret', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
