# Generated by Django 6.0.8 on 2026-10-02 10:44

from django.db import migrations, models


def _text(value):
    return (value or "").strip()


def _full_name(participant):
    title = participant.get_title_display() if participant.title else ""
    return f"{title} {participant.first_name} {participant.last_name}".strip()


def backfill(apps, schema_editor):
    """Fill the copy of every existing invoice from today's data (#761).

    Today's data is the best that is left: the issuer, IBAN and addresses an
    invoice was originally rendered with were never stored. From here on the
    copy of an approved invoice no longer changes.
    """
    Invoice = apps.get_model("invoices", "Invoice")
    Participant = apps.get_model("zev", "Participant")
    issuers = {}
    for invoice in Invoice.objects.select_related("zev", "participant").iterator(chunk_size=500):
        zev = invoice.zev
        if zev.pk not in issuers:
            party = (
                Participant.objects.filter(zev=zev, user_id=zev.owner_id)
                .order_by("last_name", "first_name", "id").first()
                if zev.owner_id else None
            )
            name = _full_name(party) if party else _text(zev.name)
            issuers[zev.pk] = {
                "name": name,
                "name_lines": [name],
                "address_line1": _text(party.address_line1) if party else "",
                "address_line2": _text(party.address_line2) if party else "",
                "postal_code": _text(party.postal_code) if party else "",
                "city": _text(party.city) if party else "",
                "email": _text(party.email) if party else "",
                "phone": _text(party.phone) if party else "",
                "iban": _text(zev.bank_iban),
                "bank_name": _text(zev.bank_name),
                "vat_number": _text(zev.vat_number),
                "zev_name": _text(zev.name),
                "from_participant": party is not None,
            }
        participant = invoice.participant
        name = _full_name(participant)
        invoice.issuer = issuers[zev.pk]
        invoice.recipient = {
            "name": name,
            "name_lines": [name],
            "title": _text(participant.title),
            "first_name": _text(participant.first_name),
            "last_name": _text(participant.last_name),
            "address_line1": _text(participant.address_line1),
            "address_line2": _text(participant.address_line2),
            "postal_code": _text(participant.postal_code),
            "city": _text(participant.city),
            "email": _text(participant.email),
        }
        invoice.save(update_fields=["issuer", "recipient"])


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_dynamic_source_evidence'),
        ('zev', '0031_zev_access_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issuer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
