# Generated by Django 6.0.3 on 2026-03-17 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zev', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('source', models.CharField(choices=[('csv', 'CSV Upload'), ('sdatch', 'SDAT-CH (ebIX XML)'), ('manual', 'Manual entry')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
                ('zev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='zev.zev')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Start of the measurement interval (UTC)')),
                ('energy_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('direction', models.CharField(choices=[('in', 'Consumption (IN)'), ('out', 'Production / Feed-in (OUT)')], default='in', max_length=5)),
                ('resolution', models.CharField(choices=[('15min', '15 minutes'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='15min', max_length=10)),
                ('import_source', models.CharField(choices=[('csv', 'CSV Upload'), ('sdatch', 'SDAT-CH (ebIX XML)'), ('manual', 'Manual entry')], default='csv', max_length=20)),
                ('import_batch', models.UUIDField(blank=True, help_text='Groups readings from the same import', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metering_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='zev.meteringpoint')),
            ],
            options={
                'ordering': ['metering_point', 'timestamp'],
                'constraints': [models.UniqueConstraint(fields=('metering_point', 'timestamp', 'direction'), name='unique_reading_per_point_time_direction')],
            },
        ),
    ]
