# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_importlog_zev_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['metering_point', 'timestamp', 'id']},
        ),
    ]
