# Generated by Django 6.0.8 on 2026-09-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0005_importlog_rows_overwritten'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='timestamp_timezone',
            field=models.CharField(blank=True, default='', help_text='Zone offset-less timestamps in this batch were read in (Europe/Zurich or UTC). Empty for imports before ADR 0026, which read them as UTC.', max_length=40),
        ),
    ]
