# Generated by Django 6.0.8 on 2026-10-08 19:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0006_importlog_timestamp_timezone'),
        ('zev', '0042_meteringpoint_building_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementarySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('solar_manager', 'Solar Manager'), ('push', 'Push or file upload')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('external_id', models.CharField(blank=True, default='', help_text='Solar Manager smId.', max_length=64)),
                ('credential_encrypted', models.BinaryField(blank=True, default=b'', help_text='Fernet ciphertext under INTEGRATION_ENCRYPTION_KEYS (ADR 0031). Never serialized.')),
                ('push_token_prefix', models.CharField(blank=True, default=None, max_length=16, null=True, unique=True)),
                ('push_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error'), ('reconnect_required', 'Reconnect required'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', help_text='User-safe text only.', max_length=500)),
                ('synced_through', models.DateTimeField(blank=True, help_text='End of the last interval ingested (UTC).', null=True)),
                ('covers_from', models.DateTimeField(blank=True, help_text='Start of the earliest stored interval (UTC).', null=True)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metering_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_source', to='zev.meteringpoint')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_sources', to='zev.participant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplementaryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Start of the measurement interval (UTC)')),
                ('consumption_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('production_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('import_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('export_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metering_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_readings', to='zev.meteringpoint')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='metering.supplementarysource')),
            ],
            options={
                'ordering': ['metering_point', 'timestamp', 'id'],
                'constraints': [models.UniqueConstraint(fields=('metering_point', 'timestamp'), name='uniq_supplementary_reading_mp_ts'), models.CheckConstraint(condition=models.Q(('consumption_kwh__gte', 0), ('production_kwh__gte', 0), ('import_kwh__gte', 0), ('export_kwh__gte', 0)), name='supplementary_reading_non_negative')],
            },
        ),
    ]
