# Generated by Django 6.0.3 on 2026-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('api_key', 'API key'), ('celery', 'Celery'), ('system', 'System'), ('management_command', 'Management command')], default='api', max_length=20),
        ),
    ]
