# Generated by Django 6.0.3 on 2026-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
