# Generated by Django 6.0.8 on 2026-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('api_key', 'API key'), ('invoice_link', 'Invoice link'), ('celery', 'Celery'), ('system', 'System'), ('management_command', 'Management command')], default='api', max_length=20),
        ),
    ]
